### ISSUE TITLE
Matlab Version

### ISSUE THREAD

**Issue by andiconda** [DrDanL/KincectViewer-Matlab#1]
Which Version do you use？

**Comment by DrDanL** [comment]
This code will have been developed using Matlab 2014b, I am aware that in the latest version there are step changes meaning it will not work.

**Comment by andiconda** [comment]
which version do you recommend？here the document is the changed one（you said), right?

**Comment by DrDanL** [comment]
I would trying Matlab 2016 initially.

**Comment by andiconda** [comment]
Cool Merci
