### ISSUE TITLE
For Run the Viewer

### ISSUE THREAD

**Issue by andiconda** [DrDanL/KincectViewer-Matlab#2]
why it read so slowly？ look like the video stalling？ are there some ways to make the viewer play smoothly？

**Comment by DrDanL** [comment]
If you take the file path and submit it to masterDisplay.m it should work. So long as you have recorded the data correctly. 

e.g. masterDisplay("kinect/recording/root")

**Comment by andiconda** [comment]
yes, I did it.
Merci.
But it runs very slow. Are there some solutions for this?

**Comment by DrDanL** [comment]
Sadly not, it is reading each file on the fly. You can use a c wrapper to read in the files to speed it up. I did not design the viewer for speed I am afraid.

**Comment by andiconda** [comment]
merci
